# Generated by Django 3.1.7 on 2021-03-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_auto_20210317_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='album',
            field=models.CharField(default='single', max_length=200),
        ),
        migrations.AddField(
            model_name='artists',
            name='genre',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='artists',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artists')),
            ],
        ),
    ]
